#!/usr/bin/env python
# Copyright (C) 2013 Eric Leblond <eric@regit.org>
#
# You can copy, redistribute or modify this Program under the terms of
# the GNU General Public License version 3 as published by the Free
# Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# version 3 along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
# 02110-1301, USA.

import suricatasc
import socket
import time

ROOT = "suricata.perf"

sc = suricatasc.SuricataSC("/usr/local/var/run/suricata/suricata-command.socket")
sc.connect()

sck = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
sck.connect(("192.168.56.101", 2003))

while 1:
    res = sc.send_command("dump-counters")
    res = res['message']
    tnow = int(time.time())
    for thread in res:
        for counter in res[thread]:
            sck.send("%s.%s.%s %s %d\n" % (ROOT, thread , counter, res[thread][counter], tnow))
    time.sleep(10)
