#!/usr/bin/env python
# Copyright (C) 2012 Eric Leblond <eric@regit.org>
#
# You can copy, redistribute or modify this Program under the terms of
# the GNU General Public License version 3 as published by the Free
# Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# version 3 along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
# 02110-1301, USA.

from suristats import *
import argparse
import os
import sys
from time import time

def start_ipython_pylab(gui):
    # Try running this code both at the command line and from inside IPython (with
    # %run example-embed.py)
    from IPython.config.loader import Config
    try:
        get_ipython
    except NameError:
        nested = 0
        cfg = Config()
        prompt_config = cfg.PromptManager
        prompt_config.in_template = 'In <\\#>: '
        prompt_config.in2_template = '   .\\D.: '
        prompt_config.out_template = 'Out<\\#>: '
    else:
        print("Running nested copies of IPython.")
        print("The prompts for the nested copy have been modified")
        cfg = Config()
        nested = 1

    from IPython.frontend.terminal.embed import InteractiveShellEmbed
    ipshell = InteractiveShellEmbed(config=cfg,
                           banner1 = 'Dropping into IPython',
                           exit_msg = 'Leaving Interpreter, back to program.')
    if gui:
        ipshell.enable_pylab(gui=gui)
    else:
        ipshell.enable_pylab()
    return ipshell

parser = argparse.ArgumentParser(prog='suri-stats', description='Statistic ang graphing tools for Suricata stats.log')
parser.add_argument('-c', '--counters', default=None, help='Counters to work on')
parser.add_argument('-s', '--stats', action='store_const', const=True, default=False, help='Output stats on file')
parser.add_argument('-p', '--plot', action='store_const', const=True, default=False, help='Plot specified counters')
parser.add_argument('-o', '--output', dest='output_file', default='out.png', help='Output file for graph')
parser.add_argument('-S', '--speed', action='store_const', const=True, default=False, help='Use computed speed not counter')
parser.add_argument('-e', '--eve', action='store_const', const=True, default=False, help='Loaded file is in JSON EVE format')
parser.add_argument('-g', '--gui', default=None, help='Pylab backend to use')
parser.add_argument('-i', '--identifier', default='Run', help='Identifier of the run')
parser.add_argument('-r', '--run', default=None, help='Suricata run to use')
parser.add_argument('-H', '--host', default='localhost', help='Identifier of host')
parser.add_argument('-V', '--version', default='HEAD', help='Identifier of version')
parser.add_argument('-I', '--initdb', default=None, help='Create the DB file specified as argument')
parser.add_argument('-U', '--updatedb', default=None, help='Update the DB file specified as argument')
parser.add_argument('-t', '--timestamp', default=time(), help='Timestamp of the run')
parser.add_argument('-v', '--verbose', action='store_const', const=True, help='verbose output', default=False)
parser.add_argument('file', metavar='file', nargs='*', help='stats.log file to parse', default=None)

args = parser.parse_args()

if args.initdb:
    DBS = DBStats(args.initdb)
    DBS.init_db()
    sys.exit(0)

ST = Stats(args.identifier)
if args.verbose:
    print "Created ST object for run '%s'" % (args.identifier)

if len(args.file) > 1:
    sys.stderr.write("Only one file supported for now\n")
    sys.exit(1)
elif len(args.file) == 1:
    [stats_file] = args.file
    if os.path.isfile(stats_file):
        if args.verbose:
            print "Loading stats.log file '%s'" % (stats_file)
        if args.eve:
            ST.load_json_file(stats_file)
        else:
            ST.load_file(stats_file)
        if len(ST.runs) > 1:
            print "WARNING: '%s' contains %d runs" % (stats_file, len(ST.runs))
    else:
        sys.stderr.write("'%s' is not a valid file, leaving\n" % (stats_file))
        sys.exit(1)
else:
    if args.verbose:
        print "No file loaded, you need to call load_file() on ST"

if args.run:
    print "Using run %d" % (int(args.run))
    ST = ST.runs[int(args.run)]

# Do we have an action asked
if args.stats:
    if len(args.file) == 0:
        sys.stderr.write("You need to specify a file\n")
        sys.exit(1)
    if args.counters:
        counters_list = args.counters.split(",")
        res_mean = ST.mean(counters_list, speed=args.speed)
        res_max = ST.max(counters_list, speed=args.speed)
        res_min = ST.min(counters_list, speed=args.speed)
        res_std = ST.std(counters_list, speed=args.speed)
    else:
        res_mean = ST.mean(speed=args.speed)
        res_max = ST.max(speed=args.speed)
        res_min = ST.min(speed=args.speed)
        res_std = ST.std(speed=args.speed)
    if args.verbose:
        print "Key:Min:Mean:Max:Std"
    for key in sorted(res_min):
        print "%s:%f:%f:%f:%f" % (key, res_min[key], res_mean[key], res_max[key], res_std[key])
elif args.plot:
    if len(args.file) == 0:
        sys.stderr.write("You need to specify a file\n")
        sys.exit(1)
    if args.counters:
        counters_list = args.counters.split(",")
        for counter in counters_list:
            if args.run:
                ST.plot(counter, speed=args.speed, filename=args.output_file)
            else:
                for run in ST.runs:
                    run.plot(counter, speed=args.speed, filename=args.output_file)
    else:
        sys.stderr.write("Nothing to plot, please specify some counters\n")
        sys.exit(1)
elif args.updatedb:
    if len(args.file) == 0:
        sys.stderr.write("You need to specify a file\n")
        sys.exit(1)
    DBS = DBStats(args.updatedb)
    if args.counters:
        counters_list = args.counters.split(",")
    else:
        counters_list = None
    DBS.update_db(ST, counters_list, args.timestamp, args.identifier, args.host, args.version, speed=args.speed)
else:
    ipshell = start_ipython_pylab(args.gui)
    ipshell('Starting interactive session')
